// ControlTwin — TwinPage.jsx — generated by Blackbox
import { useEffect, useMemo, useRef, useState } from "react";
import {
  Activity,
  CheckCircle2,
  Cpu,
  Gauge,
  Pencil,
  Plus,
  Power,
  Radio,
  RefreshCw,
  Search,
  Server,
  Trash2
} from "lucide-react";

import MetricCard from "../components/ui/MetricCard";
import StatusDot from "../components/ui/StatusDot";
import SeverityBadge from "../components/ui/SeverityBadge";
import TimeSeriesChart from "../components/charts/TimeSeriesChart";
import { Button } from "../components/ui/button";
import {
  activateTwin,
  connectTwinWebSocket,
  createTwin,
  deactivateTwin,
  deleteTwin,
  getAllTwins,
  searchTwins,
  simulateTwin,
  updateTwin,
} from "../api/twins";

const PAGE_BG = "#0A1628";
const CARD_BG = "#0F1F3D";
const BORDER = "#1B3A6B";
const ACCENT = "#00A8E8";

const ASSET_ICON = {
  turbine: <Gauge className="h-5 w-5" />,
  transformer: <Activity className="h-5 w-5" />,
  plc: <Cpu className="h-5 w-5" />,
  rtu: <Radio className="h-5 w-5" />,
  hmi: <Server className="h-5 w-5" />,
};

const EVENT_COLOR = {
  STATE_UPDATED: "text-cyan-300 border-cyan-400/30 bg-cyan-500/10",
  THRESHOLD_EXCEEDED: "text-amber-300 border-amber-400/30 bg-amber-500/10",
  DRIFT_DETECTED: "text-red-300 border-red-400/30 bg-red-500/10",
};

function toSeverity(status) {
  if (status === "critical") return "critical";
  if (status === "warning") return "medium";
  return "low";
}

function gaugeTrend(score) {
  if (score == null) return undefined;
  if (score >= 90) return { direction: "up", value: 2, label: "Excellent" };
  if (score >= 75) return { direction: "up", value: 1, label: "Stable" };
  if (score >= 55) return { direction: "down", value: 5, label: "Attention" };
  return { direction: "down", value: 12, label: "Degraded" };
}

function formatDate(value) {
  if (!value) return "-";
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? "-" : d.toLocaleString();
}

function pushSeries(existing, state) {
  const now = state?.last_updated || new Date().toISOString();
  const values = state?.current_values || {};
  const point = { name: now, ...values };
  const updated = [...existing, point];
  return updated.length > 60 ? updated.slice(updated.length - 60) : updated;
}

export default function TwinPage() {
  const [twins, setTwins] = useState([]);
  const [selectedAssetId, setSelectedAssetId] = useState("");
  const [seriesByAsset, setSeriesByAsset] = useState({});
  const [events, setEvents] = useState([]);
  const [connecting, setConnecting] = useState(true);
  const [loading, setLoading] = useState(true);

  const [query, setQuery] = useState("");
  const [newAssetInput, setNewAssetInput] = useState("");
  const [editAssetName, setEditAssetName] = useState("");
  const [message, setMessage] = useState("");

  const wsRef = useRef(null);

  const selectedTwin = useMemo(
    () => twins.find((t) => t.asset_id === selectedAssetId) || twins[0] || null,
    [twins, selectedAssetId]
  );

  useEffect(() => {
    if (selectedTwin && !editAssetName) {
      setEditAssetName(selectedTwin.asset_name || "");
    }
  }, [selectedTwin, editAssetName]);

  useEffect(() => {
    let mounted = true;
    async function bootstrap() {
      setLoading(true);
      try {
        const data = await getAllTwins();
        if (!mounted) return;
        const topFive = (data || []).slice(0, 5);
        setTwins(topFive);
        if (topFive.length && !selectedAssetId) setSelectedAssetId(topFive[0].asset_id);
      } finally {
        if (mounted) setLoading(false);
      }
    }
    bootstrap();
    return () => {
      mounted = false;
    };
  }, []);

  useEffect(() => {
    const ws = connectTwinWebSocket((messageWs) => {
      if (messageWs?.type !== "live_states") return;
      const states = messageWs?.data || [];
      const topFive = states.slice(0, 5);
      setTwins(topFive);
      setConnecting(false);

      setSeriesByAsset((prev) => {
        const next = { ...prev };
        topFive.forEach((state) => {
          const key = state.asset_id;
          const existing = next[key] || [];
          next[key] = pushSeries(existing, state);
        });
        return next;
      });

      setEvents((prev) => {
        const generated = [];
        for (const s of topFive) {
          generated.push({
            id: `${s.asset_id}-${s.last_updated}-STATE_UPDATED`,
            event_type: "STATE_UPDATED",
            asset_id: s.asset_id,
            timestamp: s.last_updated,
            payload: { status: s.status, health_score: s.health_score, drift: s.drift },
          });
          if (s.status === "warning" || s.status === "critical") {
            generated.push({
              id: `${s.asset_id}-${s.last_updated}-THRESHOLD_EXCEEDED`,
              event_type: "THRESHOLD_EXCEEDED",
              asset_id: s.asset_id,
              timestamp: s.last_updated,
              payload: { status: s.status },
            });
          }
          if ((s.drift || 0) > 20) {
            generated.push({
              id: `${s.asset_id}-${s.last_updated}-DRIFT_DETECTED`,
              event_type: "DRIFT_DETECTED",
              asset_id: s.asset_id,
              timestamp: s.last_updated,
              payload: { drift: s.drift },
            });
          }
        }
        return [...generated.reverse(), ...prev].slice(0, 20);
      });
    });

    ws.onopen = () => setConnecting(false);
    ws.onclose = () => setConnecting(true);
    ws.onerror = () => setConnecting(true);
    wsRef.current = ws;

    const fallback = setInterval(async () => {
      if (ws.readyState === WebSocket.OPEN) return;
      try {
        const data = await getAllTwins();
        setTwins((data || []).slice(0, 5));
      } catch {
        // no-op
      }
    }, 2000);

    return () => {
      clearInterval(fallback);
      if (wsRef.current) wsRef.current.close();
    };
  }, []);

  const chartData = useMemo(() => {
    if (!selectedTwin) return [];
    return seriesByAsset[selectedTwin.asset_id] || [];
  }, [selectedTwin, seriesByAsset]);

  const chartTags = useMemo(() => {
    if (!chartData.length) return [];
    return Object.keys(chartData[0]).filter((k) => k !== "name");
  }, [chartData]);

  async function onSimulate(assetId) {
    if (!assetId) return;
    const state = await simulateTwin(assetId, 10);
    setTwins((prev) => prev.map((t) => (t.asset_id === assetId ? state : t)));
    setSeriesByAsset((prev) => {
      const existing = prev[assetId] || [];
      return { ...prev, [assetId]: pushSeries(existing, state) };
    });
    setMessage("Simulation exécutée.");
  }

  async function onSearch() {
    const data = await searchTwins(query);
    const topFive = (data || []).slice(0, 5);
    setTwins(topFive);
    if (topFive.length) setSelectedAssetId(topFive[0].asset_id);
    setMessage(`Recherche: ${topFive.length} twin(s) trouvé(s).`);
  }

  async function onCreateTwin() {
    const raw = (newAssetInput || "").trim();
    if (!raw) {
      setMessage("Veuillez saisir un nom, tag ou UUID d'équipement.");
      return;
    }

    try {
      await createTwin(raw);
      const refreshed = await getAllTwins();
      const topFive = (refreshed || []).slice(0, 5);
      setTwins(topFive);
      const created = topFive.find((t) => t.asset_id === raw);
      if (created) {
        setSelectedAssetId(created.asset_id);
        setEditAssetName(created.asset_name || "");
      } else if (topFive.length) {
        setSelectedAssetId(topFive[0].asset_id);
      }
      setMessage("Twin ajouté.");
      setNewAssetInput("");
    } catch (error) {
      const detail =
        error?.response?.data?.detail ||
        error?.message ||
        "Échec de création du twin.";
      setMessage(`Erreur Add: ${detail}`);
    }
  }

  async function onUpdateTwin() {
    if (!selectedTwin) return;
    const updated = await updateTwin(selectedTwin.asset_id, {
      asset_name: editAssetName || selectedTwin.asset_name,
      current_values: selectedTwin.current_values || {},
    });
    setTwins((prev) => prev.map((t) => (t.asset_id === selectedTwin.asset_id ? updated : t)));
    setMessage("Twin modifié.");
  }

  async function onDeleteTwin() {
    if (!selectedTwin) return;
    await deleteTwin(selectedTwin.asset_id);
    const refreshed = await getAllTwins();
    const topFive = (refreshed || []).slice(0, 5);
    setTwins(topFive);
    setSelectedAssetId(topFive[0]?.asset_id || "");
    setMessage("Twin supprimé/réinitialisé.");
  }

  async function onToggleActive() {
    if (!selectedTwin) return;
    const isActive = selectedTwin.status !== "critical";
    if (isActive) {
      await deactivateTwin(selectedTwin.asset_id);
      setMessage("Twin désactivé.");
    } else {
      await activateTwin(selectedTwin.asset_id);
      setMessage("Twin activé.");
    }
    const refreshed = await getAllTwins();
    setTwins((refreshed || []).slice(0, 5));
  }

  return (
    <div className="min-h-screen p-6 text-white" style={{ background: PAGE_BG }}>
      <div
        className="mb-6 rounded-2xl border p-4 md:p-5"
        style={{ borderColor: BORDER, background: "linear-gradient(135deg, #0F1F3D 0%, #10264B 100%)" }}
      >
        <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Digital Twin Command Center</h1>
            <p className="mt-1 text-sm text-slate-300">
              Real-time monitoring, simulation and lifecycle management for critical assets.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <StatusDot status={connecting ? "offline" : "online"} label size="sm" />
            <div className="inline-flex items-center gap-2 rounded-lg border px-3 py-1.5 text-xs" style={{ borderColor: BORDER }}>
              <CheckCircle2 className="h-3.5 w-3.5 text-cyan-300" />
              <span className="text-slate-200">{selectedTwin ? selectedTwin.asset_name : "No twin selected"}</span>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-6">
          <div className="flex gap-2 xl:col-span-2">
            <input
              className="w-full rounded-md border bg-[#0A1628] px-3 py-2 text-sm"
              style={{ borderColor: BORDER }}
              placeholder="Search by name/tag/type"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
            <Button onClick={onSearch} className="min-w-24">
              <Search className="mr-2 h-4 w-4" />
              Search
            </Button>
          </div>

          <div className="flex gap-2 xl:col-span-2">
            <input
              className="w-full rounded-md border bg-[#0A1628] px-3 py-2 text-sm"
              style={{ borderColor: BORDER }}
              placeholder="Asset name/tag or UUID to add twin"
              value={newAssetInput}
              onChange={(e) => setNewAssetInput(e.target.value)}
            />
            <Button onClick={onCreateTwin} className="min-w-24">
              <Plus className="mr-2 h-4 w-4" />
              Add
            </Button>
          </div>

          <Button onClick={() => selectedTwin && onSimulate(selectedTwin.asset_id)} disabled={!selectedTwin}>
            <RefreshCw className="mr-2 h-4 w-4" />
            Simulate
          </Button>

          <Button onClick={onUpdateTwin} disabled={!selectedTwin} variant="outline">
            <Pencil className="mr-2 h-4 w-4" />
            Edit
          </Button>

          <Button onClick={onDeleteTwin} disabled={!selectedTwin} variant="outline">
            <Trash2 className="mr-2 h-4 w-4" />
            Delete
          </Button>

          <Button onClick={onToggleActive} disabled={!selectedTwin} variant="outline">
            <Power className="mr-2 h-4 w-4" />
            Toggle
          </Button>
        </div>
      </div>

      {message ? (
        <div className="mb-4 rounded-md border px-3 py-2 text-sm" style={{ borderColor: BORDER, background: CARD_BG }}>
          {message}
        </div>
      ) : null}

      <div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5">
        {(twins || []).slice(0, 5).map((asset) => (
          <div
            key={asset.asset_id}
            className="rounded-xl border p-1"
            style={{
              borderColor: BORDER,
              background: CARD_BG,
              boxShadow: `0 0 0 1px ${selectedAssetId === asset.asset_id ? ACCENT : "transparent"}`,
            }}
          >
            <MetricCard
              title={asset.asset_name || asset.asset_type}
              value={Math.round(asset.health_score ?? 0)}
              unit="/100"
              icon={ASSET_ICON[(asset.asset_type || "").toLowerCase()] || <Activity className="h-5 w-5" />}
              iconColor="text-cyan-300"
              trend={gaugeTrend(asset.health_score)}
              onClick={() => {
                setSelectedAssetId(asset.asset_id);
                setEditAssetName(asset.asset_name || "");
              }}
              loading={loading}
            />
            <div className="px-6 pb-4">
              <div className="mb-2 flex items-center justify-between">
                <StatusDot status={asset.status === "normal" ? "online" : "degraded"} label={false} />
                <SeverityBadge severity={toSeverity(asset.status)} />
              </div>
              <p className="text-xs text-slate-400">Last updated: {formatDate(asset.last_updated)}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="mb-6 rounded-xl border p-4" style={{ borderColor: BORDER, background: CARD_BG }}>
        <div className="mb-3 flex flex-wrap items-center justify-between gap-3">
          <h2 className="text-lg font-medium">Real-time Metrics {selectedTwin ? `— ${selectedTwin.asset_name}` : ""}</h2>
          <select
            className="rounded-md border bg-[#0A1628] px-3 py-2 text-sm text-slate-100"
            style={{ borderColor: BORDER }}
            value={selectedTwin?.asset_id || ""}
            onChange={(e) => setSelectedAssetId(e.target.value)}
          >
            {(twins || []).map((t) => (
              <option key={t.asset_id} value={t.asset_id}>
                {t.asset_name} ({t.asset_type})
              </option>
            ))}
          </select>
        </div>
        <TimeSeriesChart data={chartData} loading={loading} tags={chartTags} />
      </div>

      <div className="mb-6 rounded-xl border p-4" style={{ borderColor: BORDER, background: CARD_BG }}>
        <h2 className="mb-3 text-lg font-medium">Twin Management</h2>
        <div className="mb-4 grid grid-cols-1 gap-3 md:grid-cols-2">
          <input
            className="rounded-md border bg-[#0A1628] px-3 py-2 text-sm"
            style={{ borderColor: BORDER }}
            placeholder="Edit twin display name"
            value={editAssetName}
            onChange={(e) => setEditAssetName(e.target.value)}
          />
          <div className="rounded-md border px-3 py-2 text-sm text-slate-300" style={{ borderColor: BORDER, background: "#0A1628" }}>
            Use the action bar above for Add / Search / Simulate / Edit / Delete / Toggle.
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b" style={{ borderColor: BORDER }}>
                <th className="px-2 py-2">Asset ID</th>
                <th className="px-2 py-2">Name</th>
                <th className="px-2 py-2">Type</th>
                <th className="px-2 py-2">Status</th>
                <th className="px-2 py-2">Health</th>
                <th className="px-2 py-2">Updated</th>
              </tr>
            </thead>
            <tbody>
              {(twins || []).map((t) => (
                <tr
                  key={t.asset_id}
                  className="cursor-pointer border-b hover:bg-slate-700/20"
                  style={{ borderColor: BORDER }}
                  onClick={() => {
                    setSelectedAssetId(t.asset_id);
                    setEditAssetName(t.asset_name || "");
                  }}
                >
                  <td className="px-2 py-2 font-mono text-xs">{t.asset_id}</td>
                  <td className="px-2 py-2">{t.asset_name}</td>
                  <td className="px-2 py-2">{t.asset_type}</td>
                  <td className="px-2 py-2">
                    <SeverityBadge severity={toSeverity(t.status)} />
                  </td>
                  <td className="px-2 py-2">{Math.round(t.health_score || 0)}</td>
                  <td className="px-2 py-2">{formatDate(t.last_updated)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="rounded-xl border p-4" style={{ borderColor: BORDER, background: CARD_BG }}>
        <h2 className="mb-3 text-lg font-medium">Twin Event Log (last 20)</h2>
        <div className="space-y-2">
          {(events || []).slice(0, 20).map((evt) => (
            <div
              key={evt.id}
              className={`rounded-lg border px-3 py-2 text-sm ${
                EVENT_COLOR[evt.event_type] || "text-slate-200 border-slate-600/30 bg-slate-500/10"
              }`}
            >
              <div className="flex items-center justify-between gap-3">
                <span className="font-semibold">{evt.event_type}</span>
                <span className="text-xs opacity-80">{formatDate(evt.timestamp)}</span>
              </div>
              <div className="mt-1 text-xs opacity-90">
                Asset: {evt.asset_id} — Payload: {JSON.stringify(evt.payload)}
              </div>
            </div>
          ))}
          {!events.length && <p className="text-sm text-slate-400">No events yet.</p>}
        </div>
      </div>
    </div>
  );
}
