# ControlTwin — simulator.py — generated by Blackbox
"""Digital Twin simulator producing realistic synthetic datapoints."""

from __future__ import annotations

import random
from datetime import datetime, timezone
from typing import Any

import numpy as np


def utcnow() -> datetime:
    """Return current UTC datetime."""
    return datetime.now(timezone.utc)


class TwinSimulator:
    """Generate synthetic datapoints for supported asset classes."""

    def __init__(self, anomaly_probability: float = 0.05) -> None:
        self.anomaly_probability = anomaly_probability

    async def simulate_asset(self, asset_id: str, asset_type: str, n_points: int = 10) -> list[dict[str, Any]]:
        """Simulate N datapoint samples for an asset."""
        kind = asset_type.lower()
        samples: list[dict[str, Any]] = []
        for _ in range(max(1, n_points)):
            point = self._simulate_point(kind)
            point["asset_id"] = asset_id
            point["timestamp"] = utcnow().isoformat()
            samples.append(point)
        return samples

    def _simulate_point(self, asset_type: str) -> dict[str, Any]:
        if asset_type == "turbine":
            base = {
                "temperature": self._gauss_clip(86, 10, 60, 115),
                "vibration": self._gauss_clip(6, 2, 2, 12),
                "rpm": self._gauss_clip(2800, 350, 1800, 3600),
                "input_power": self._gauss_clip(120, 20, 80, 180),
                "output_power": self._gauss_clip(105, 18, 60, 160),
            }
        elif asset_type == "transformer":
            base = {
                "temperature": self._gauss_clip(62, 8, 40, 80),
                "oil_level": self._gauss_clip(90, 3, 82, 98),
                "load": self._gauss_clip(68, 15, 30, 95),
                "voltage": self._gauss_clip(132, 8, 110, 160),
            }
        elif asset_type == "plc":
            base = {
                "cpu_usage": self._gauss_clip(45, 12, 10, 75),
                "memory_usage": self._gauss_clip(42, 10, 20, 60),
                "scan_time": self._gauss_clip(35, 8, 8, 120),
                "io_errors": int(self._gauss_clip(1, 1.5, 0, 12)),
            }
        elif asset_type == "rtu":
            base = {
                "signal_strength": self._gauss_clip(-72, 5, -85, -60),
                "packet_loss": self._gauss_clip(1.0, 0.8, 0, 3),
                "latency": self._gauss_clip(70, 18, 20, 220),
            }
        elif asset_type == "hmi":
            base = {
                "response_time": self._gauss_clip(700, 250, 200, 1500),
                "active_sessions": int(self._gauss_clip(18, 7, 1, 120)),
                "availability": self._gauss_clip(99.7, 0.2, 98.8, 100.0),
            }
        else:
            base = {
                "value": self._gauss_clip(50, 10, 0, 100),
            }

        if random.random() < self.anomaly_probability:
            base = self._inject_anomaly(asset_type, base)

        return base

    def _inject_anomaly(self, asset_type: str, sample: dict[str, Any]) -> dict[str, Any]:
        """Introduce occasional spikes/dropouts."""
        s = dict(sample)

        if asset_type == "turbine":
            s["temperature"] = min(160.0, float(s["temperature"]) + random.uniform(20, 45))
            s["vibration"] = min(30.0, float(s["vibration"]) + random.uniform(5, 15))
        elif asset_type == "transformer":
            s["temperature"] = min(120.0, float(s["temperature"]) + random.uniform(10, 35))
            s["oil_level"] = max(50.0, float(s["oil_level"]) - random.uniform(8, 25))
        elif asset_type == "plc":
            s["cpu_usage"] = min(100.0, float(s["cpu_usage"]) + random.uniform(20, 40))
            s["memory_usage"] = min(100.0, float(s["memory_usage"]) + random.uniform(15, 35))
            s["io_errors"] = int(float(s["io_errors"]) + random.uniform(8, 30))
        elif asset_type == "rtu":
            s["signal_strength"] = max(-120.0, float(s["signal_strength"]) - random.uniform(10, 25))
            s["packet_loss"] = min(35.0, float(s["packet_loss"]) + random.uniform(5, 20))
            s["latency"] = min(2000.0, float(s["latency"]) + random.uniform(100, 600))
        elif asset_type == "hmi":
            s["response_time"] = min(5000.0, float(s["response_time"]) + random.uniform(800, 2500))
            s["availability"] = max(85.0, float(s["availability"]) - random.uniform(1.5, 8))

        return s

    def _gauss_clip(self, mean: float, sigma: float, low: float, high: float) -> float:
        """Sample gaussian value and clamp to realistic engineering range."""
        value = float(np.random.normal(loc=mean, scale=sigma))
        return float(np.clip(value, low, high))
