# ControlTwin — twin_engine.py — generated by Blackbox
"""In-memory Digital Twin engine with derived metrics and event emission."""

from __future__ import annotations

from collections import deque
from datetime import datetime, timezone
from threading import Lock
from typing import Any

from app.twins.twin_models import (
    DEFAULT_THRESHOLDS_BY_ASSET_TYPE,
    TwinBaseline,
    TwinEvent,
    TwinState,
)


def utcnow() -> datetime:
    """Return current UTC datetime."""
    return datetime.now(timezone.utc)


class DigitalTwinEngine:
    """Singleton Digital Twin engine (one instance per process)."""

    _instance: "DigitalTwinEngine | None" = None
    _instance_lock = Lock()

    def __new__(cls) -> "DigitalTwinEngine":
        with cls._instance_lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._initialized = False
        return cls._instance

    def __init__(self) -> None:
        if getattr(self, "_initialized", False):
            return
        self._states: dict[str, TwinState] = {}
        self._buffers: dict[str, deque[dict[str, Any]]] = {}
        self._history: dict[str, deque[TwinState]] = {}
        self._events: deque[TwinEvent] = deque(maxlen=2000)
        self._baselines: dict[str, dict[str, TwinBaseline]] = {}
        self._asset_meta: dict[str, tuple[str, str]] = {}
        self._lock = Lock()
        self._initialized = True

    async def update_state(
        self,
        asset_id: str,
        datapoints: dict[str, float | int | bool | str],
        asset_name: str | None = None,
        asset_type: str | None = None,
    ) -> TwinState:
        """Update asset state from incoming datapoints and return latest state."""
        with self._lock:
            name, kind = self._asset_meta.get(asset_id, (asset_name or asset_id, (asset_type or "unknown").lower()))
            if asset_name:
                name = asset_name
            if asset_type:
                kind = asset_type.lower()
            self._asset_meta[asset_id] = (name, kind)

            if asset_id not in self._buffers:
                self._buffers[asset_id] = deque(maxlen=100)
            self._buffers[asset_id].append(
                {
                    "timestamp": utcnow().isoformat(),
                    "values": datapoints,
                }
            )

            prev_values = self._states.get(asset_id).current_values if asset_id in self._states else {}
            merged_values: dict[str, float | int | bool | str] = {**prev_values, **datapoints}

            efficiency = self._compute_efficiency(merged_values)
            health_score = self._compute_health_score(kind, merged_values)
            drift = self._compute_drift(asset_id, merged_values)
            status = self._compute_status(kind, merged_values, health_score, drift)

            state = TwinState(
                asset_id=asset_id,
                asset_name=name,
                asset_type=kind,
                last_updated=utcnow(),
                health_score=health_score,
                efficiency=efficiency,
                drift=drift,
                current_values=merged_values,
                status=status,
            )
            self._states[asset_id] = state

            if asset_id not in self._history:
                self._history[asset_id] = deque(maxlen=1000)
            self._history[asset_id].append(state)

            self._events.append(
                TwinEvent(
                    event_type="STATE_UPDATED",
                    asset_id=asset_id,
                    payload={"status": state.status, "health_score": state.health_score},
                )
            )

            threshold_breaches = self._check_thresholds(kind, merged_values)
            if threshold_breaches:
                self._events.append(
                    TwinEvent(
                        event_type="THRESHOLD_EXCEEDED",
                        asset_id=asset_id,
                        payload={"breaches": threshold_breaches},
                    )
                )

            if drift is not None and drift > 20.0:
                self._events.append(
                    TwinEvent(
                        event_type="DRIFT_DETECTED",
                        asset_id=asset_id,
                        payload={"drift": drift},
                    )
                )

            return state

    async def get_state(self, asset_id: str) -> TwinState | None:
        """Get current state for one asset."""
        with self._lock:
            return self._states.get(asset_id)

    async def get_all_states(self) -> list[TwinState]:
        """Get current states for all tracked assets."""
        with self._lock:
            return list(self._states.values())

    async def get_history(self, asset_id: str, n: int = 100) -> list[TwinState]:
        """Get latest N historical snapshots for an asset."""
        with self._lock:
            history = list(self._history.get(asset_id, deque()))
            if n <= 0:
                return []
            return history[-n:]

    async def get_baseline(self, asset_id: str) -> list[TwinBaseline]:
        """Get current baseline set for asset."""
        with self._lock:
            return list(self._baselines.get(asset_id, {}).values())

    async def compute_baseline(self, asset_id: str) -> list[TwinBaseline]:
        """Compute baseline values from buffer averages."""
        with self._lock:
            buffer = self._buffers.get(asset_id)
            if not buffer:
                return []

            samples: list[dict[str, Any]] = [item["values"] for item in buffer]
            numeric_by_tag: dict[str, list[float]] = {}
            for sample in samples:
                for tag, value in sample.items():
                    if isinstance(value, (int, float)) and not isinstance(value, bool):
                        numeric_by_tag.setdefault(tag, []).append(float(value))

            computed: dict[str, TwinBaseline] = {}
            for tag, vals in numeric_by_tag.items():
                if not vals:
                    continue
                computed[tag] = TwinBaseline(
                    asset_id=asset_id,
                    tag_name=tag,
                    baseline_value=sum(vals) / len(vals),
                )
            self._baselines[asset_id] = computed
            return list(computed.values())

    async def reset_state(self, asset_id: str) -> None:
        """Reset state, history and buffer for one asset."""
        with self._lock:
            self._states.pop(asset_id, None)
            self._buffers.pop(asset_id, None)
            self._history.pop(asset_id, None)
            self._baselines.pop(asset_id, None)
            self._asset_meta.pop(asset_id, None)

    async def get_recent_events(self, n: int = 20) -> list[TwinEvent]:
        """Get last N events globally."""
        with self._lock:
            if n <= 0:
                return []
            return list(self._events)[-n:]

    def _compute_efficiency(self, values: dict[str, Any]) -> float | None:
        inp = values.get("input_power")
        out = values.get("output_power")
        if isinstance(inp, (int, float)) and isinstance(out, (int, float)) and float(inp) != 0.0:
            return max(0.0, min(100.0, float(out) / float(inp) * 100.0))
        return None

    def _compute_health_score(self, asset_type: str, values: dict[str, Any]) -> float:
        thresholds = DEFAULT_THRESHOLDS_BY_ASSET_TYPE.get(asset_type.lower(), [])
        if not thresholds:
            numeric_vals = [float(v) for v in values.values() if isinstance(v, (int, float)) and not isinstance(v, bool)]
            if not numeric_vals:
                return 100.0
            return max(0.0, min(100.0, 100.0 - (sum(abs(v) for v in numeric_vals) / (len(numeric_vals) * 100.0)) * 100.0))

        scores: list[float] = []
        for threshold in thresholds:
            current = values.get(threshold.tag_name)
            if not isinstance(current, (int, float)) or isinstance(current, bool):
                continue
            val = float(current)

            min_val = threshold.min_val
            max_val = threshold.max_val

            if min_val is None and max_val is None:
                scores.append(100.0)
                continue

            if min_val is not None and max_val is not None:
                mid = (min_val + max_val) / 2.0
                half_span = max((max_val - min_val) / 2.0, 1e-6)
                deviation = abs(val - mid) / half_span
                score = max(0.0, 100.0 * (1.0 - min(deviation, 1.0)))
                scores.append(score)
            elif max_val is not None:
                if val <= max_val:
                    score = max(0.0, 100.0 - (val / max(max_val, 1e-6)) * 20.0)
                else:
                    overshoot = (val - max_val) / max(max_val, 1e-6)
                    score = max(0.0, 80.0 - overshoot * 100.0)
                scores.append(score)
            else:
                if val >= min_val:
                    score = max(0.0, 100.0 - (abs(val - min_val) / max(abs(min_val), 1.0)) * 20.0)
                else:
                    undershoot = (min_val - val) / max(abs(min_val), 1.0)
                    score = max(0.0, 80.0 - undershoot * 100.0)
                scores.append(score)

        if not scores:
            return 100.0

        weight = 1.0 / len(scores)
        weighted_sum = sum(s * weight for s in scores)
        return max(0.0, min(100.0, weighted_sum))

    def _compute_drift(self, asset_id: str, values: dict[str, Any]) -> float | None:
        baselines = self._baselines.get(asset_id)
        if not baselines:
            return None

        drifts: list[float] = []
        for tag, baseline in baselines.items():
            current = values.get(tag)
            if not isinstance(current, (int, float)) or isinstance(current, bool):
                continue
            b = baseline.baseline_value
            if b == 0:
                continue
            drifts.append(abs(float(current) - b) / abs(b) * 100.0)

        if not drifts:
            return None
        return sum(drifts) / len(drifts)

    def _check_thresholds(self, asset_type: str, values: dict[str, Any]) -> list[dict[str, Any]]:
        thresholds = DEFAULT_THRESHOLDS_BY_ASSET_TYPE.get(asset_type.lower(), [])
        breaches: list[dict[str, Any]] = []
        for threshold in thresholds:
            value = values.get(threshold.tag_name)
            if not isinstance(value, (int, float)) or isinstance(value, bool):
                continue
            fv = float(value)
            if threshold.min_val is not None and fv < threshold.min_val:
                breaches.append(
                    {
                        "tag_name": threshold.tag_name,
                        "value": fv,
                        "limit": threshold.min_val,
                        "direction": "below_min",
                        "unit": threshold.unit,
                    }
                )
            if threshold.max_val is not None and fv > threshold.max_val:
                breaches.append(
                    {
                        "tag_name": threshold.tag_name,
                        "value": fv,
                        "limit": threshold.max_val,
                        "direction": "above_max",
                        "unit": threshold.unit,
                    }
                )
        return breaches

    def _compute_status(
        self,
        asset_type: str,
        values: dict[str, Any],
        health_score: float | None,
        drift: float | None,
    ) -> str:
        breaches = self._check_thresholds(asset_type, values)
        if breaches:
            severe = any(b["direction"] == "above_max" and b["tag_name"] in {"temperature", "vibration", "cpu_usage"} for b in breaches)
            if severe:
                return "critical"
            return "warning"

        if health_score is not None:
            if health_score < 50.0:
                return "critical"
            if health_score < 75.0:
                return "warning"

        if drift is not None:
            if drift > 40.0:
                return "critical"
            if drift > 20.0:
                return "warning"

        return "normal"
