# ControlTwin — twin_models.py — generated by Blackbox
"""Digital Twin Pydantic models and default thresholds."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


def utcnow() -> datetime:
    """Return current UTC datetime."""
    return datetime.now(timezone.utc)


class TwinThreshold(BaseModel):
    """Threshold definition for a telemetry tag."""

    model_config = ConfigDict(extra="forbid")

    tag_name: str
    min_val: float | None = None
    max_val: float | None = None
    unit: str


class TwinBaseline(BaseModel):
    """Baseline value for drift computation."""

    model_config = ConfigDict(extra="forbid")

    asset_id: str
    tag_name: str
    baseline_value: float
    computed_at: datetime = Field(default_factory=utcnow)


class TwinEvent(BaseModel):
    """Event emitted by the twin engine."""

    model_config = ConfigDict(extra="allow")

    event_type: Literal["STATE_UPDATED", "THRESHOLD_EXCEEDED", "DRIFT_DETECTED"]
    asset_id: str
    timestamp: datetime = Field(default_factory=utcnow)
    payload: dict[str, Any] = Field(default_factory=dict)


class TwinState(BaseModel):
    """Current digital twin state for one asset."""

    model_config = ConfigDict(extra="allow")

    asset_id: str
    asset_name: str
    asset_tag: str | None = None
    asset_type: str
    last_updated: datetime = Field(default_factory=utcnow)
    health_score: float | None = None
    efficiency: float | None = None
    drift: float | None = None
    current_values: dict[str, float | int | bool | str] = Field(default_factory=dict)
    status: Literal["normal", "warning", "critical"] = "normal"


DEFAULT_THRESHOLDS_BY_ASSET_TYPE: dict[str, list[TwinThreshold]] = {
    "turbine": [
        TwinThreshold(tag_name="temperature", min_val=None, max_val=120.0, unit="°C"),
        TwinThreshold(tag_name="vibration", min_val=None, max_val=15.0, unit="mm/s"),
        TwinThreshold(tag_name="rpm", min_val=1200.0, max_val=3600.0, unit="rpm"),
    ],
    "transformer": [
        TwinThreshold(tag_name="temperature", min_val=None, max_val=85.0, unit="°C"),
        TwinThreshold(tag_name="oil_level", min_val=80.0, max_val=None, unit="%"),
        TwinThreshold(tag_name="load", min_val=None, max_val=100.0, unit="%"),
    ],
    "plc": [
        TwinThreshold(tag_name="cpu_usage", min_val=None, max_val=90.0, unit="%"),
        TwinThreshold(tag_name="memory_usage", min_val=None, max_val=85.0, unit="%"),
    ],
    "rtu": [
        TwinThreshold(tag_name="signal_strength", min_val=-90.0, max_val=None, unit="dBm"),
        TwinThreshold(tag_name="packet_loss", min_val=None, max_val=5.0, unit="%"),
    ],
    "hmi": [
        TwinThreshold(tag_name="response_time", min_val=None, max_val=2000.0, unit="ms"),
        TwinThreshold(tag_name="availability", min_val=99.0, max_val=None, unit="%"),
    ],
}
