# ControlTwin — twin_store.py — generated by Blackbox
"""Redis-backed store for Digital Twin states, history, and events."""

from __future__ import annotations

import json
import logging
from collections.abc import Callable
from typing import Any

from redis.asyncio import Redis
from redis.exceptions import RedisError

from app.core.config import settings
from app.twins.twin_models import TwinEvent, TwinState


logger = logging.getLogger(__name__)


class TwinStore:
    """Redis persistence and pub/sub for twin runtime data."""

    def __init__(self, redis_factory: Callable[[], Redis] | None = None) -> None:
        self._redis_factory = redis_factory
        self._redis: Redis | None = None

    async def _client(self) -> Redis | None:
        if self._redis is None:
            try:
                if self._redis_factory:
                    self._redis = self._redis_factory()
                else:
                    self._redis = Redis.from_url(settings.REDIS_URL, decode_responses=True)
                await self._redis.ping()
            except RedisError as exc:
                logger.warning("Redis unavailable, TwinStore running in degraded mode: %s", exc)
                self._redis = None
        return self._redis

    async def save_state(self, asset_id: str, state: TwinState) -> None:
        """Store current state with 1h TTL."""
        client = await self._client()
        if client is None:
            return
        key = f"twin:state:{asset_id}"
        try:
            await client.set(key, state.model_dump_json(), ex=3600)
        except RedisError as exc:
            logger.warning("Redis save_state failed for %s: %s", asset_id, exc)

    async def get_state(self, asset_id: str) -> TwinState | None:
        """Fetch one twin state from Redis."""
        client = await self._client()
        if client is None:
            return None
        key = f"twin:state:{asset_id}"
        try:
            payload = await client.get(key)
        except RedisError as exc:
            logger.warning("Redis get_state failed for %s: %s", asset_id, exc)
            return None
        if not payload:
            return None
        return TwinState.model_validate_json(payload)

    async def save_snapshot(self, asset_id: str, state: TwinState) -> None:
        """Append state snapshot to history list and trim to last 1000 items."""
        client = await self._client()
        if client is None:
            return
        key = f"twin:history:{asset_id}"
        try:
            await client.lpush(key, state.model_dump_json())
            await client.ltrim(key, 0, 999)
        except RedisError as exc:
            logger.warning("Redis save_snapshot failed for %s: %s", asset_id, exc)

    async def get_history(self, asset_id: str, n: int = 100) -> list[TwinState]:
        """Return latest N snapshots for asset (newest first)."""
        client = await self._client()
        if client is None:
            return []
        key = f"twin:history:{asset_id}"
        count = max(1, n)
        try:
            rows = await client.lrange(key, 0, count - 1)
        except RedisError as exc:
            logger.warning("Redis get_history failed for %s: %s", asset_id, exc)
            return []
        states: list[TwinState] = []
        for row in rows:
            try:
                states.append(TwinState.model_validate_json(row))
            except Exception:
                continue
        return states

    async def publish_event(self, event: TwinEvent) -> None:
        """Publish event to twin:events channel."""
        client = await self._client()
        if client is None:
            return
        try:
            await client.publish("twin:events", event.model_dump_json())
        except RedisError as exc:
            logger.warning("Redis publish_event failed: %s", exc)

    async def close(self) -> None:
        """Close Redis connection."""
        if self._redis is not None:
            try:
                await self._redis.close()
            except RedisError as exc:
                logger.warning("Redis close failed: %s", exc)
            self._redis = None

    @staticmethod
    def to_json(value: dict[str, Any]) -> str:
        """Serialize dict to JSON string."""
        return json.dumps(value, ensure_ascii=False)
