# ControlTwin — twins.py — generated by Blackbox
"""Digital Twin endpoints and live WebSocket stream."""

from __future__ import annotations

import asyncio
import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, ConfigDict

from fastapi import APIRouter, Depends, HTTPException, Query, WebSocket, WebSocketDisconnect
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.dependencies import get_current_user
from app.db.postgres import get_session
from app.models.models import Asset, AssetStatus, User
from app.twins.simulator import TwinSimulator
from app.twins.twin_engine import DigitalTwinEngine
from app.twins.twin_models import TwinBaseline, TwinState
from app.twins.twin_store import TwinStore

router = APIRouter(prefix="/twins", tags=["twins"])


def utcnow() -> datetime:
    """Return current UTC datetime."""
    return datetime.now(timezone.utc)


engine = DigitalTwinEngine()
simulator = TwinSimulator()
store = TwinStore()


class TwinCreateRequest(BaseModel):
    """Payload to create/init a twin state for an existing asset."""

    model_config = ConfigDict(extra="forbid")

    asset_id: uuid.UUID | None = None
    asset_query: str | None = None


class TwinUpdateRequest(BaseModel):
    """Payload to update twin metadata and/or values."""

    model_config = ConfigDict(extra="forbid")

    asset_name: str | None = None
    current_values: dict[str, float | int | bool | str] | None = None


def _asset_to_twin(asset: Asset) -> TwinState:
    return TwinState(
        asset_id=str(asset.id),
        asset_name=asset.name,
        asset_type=asset.asset_type.value if hasattr(asset.asset_type, "value") else str(asset.asset_type),
        last_updated=utcnow(),
        current_values={},
        status="normal",
    )


@router.get("/", response_model=list[TwinState])
async def list_twins(
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> list[TwinState]:
    """List all in-memory twin states."""
    states = await engine.get_all_states()
    if states:
        return states

    assets = (await session.execute(select(Asset).where(Asset.is_active.is_(True)))).scalars().all()
    return [_asset_to_twin(asset) for asset in assets]


@router.get("/{asset_id}", response_model=TwinState)
async def get_twin(
    asset_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> TwinState:
    """Get state for one asset id."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    state = await engine.get_state(str(asset_id))
    if state:
        return state

    redis_state = await store.get_state(str(asset_id))
    if redis_state:
        return redis_state

    return TwinState(
        asset_id=str(asset.id),
        asset_name=asset.name,
        asset_type=asset.asset_type.value if hasattr(asset.asset_type, "value") else str(asset.asset_type),
        last_updated=utcnow(),
        current_values={},
        status="normal",
    )


@router.get("/search", response_model=list[TwinState])
async def search_twins(
    q: str = Query(default="", min_length=0),
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> list[TwinState]:
    """Search twins by asset name/tag/type."""
    query = select(Asset).where(Asset.is_active.is_(True))
    assets = (await session.execute(query)).scalars().all()
    if not q.strip():
        return [_asset_to_twin(asset) for asset in assets]

    needle = q.strip().lower()
    filtered: list[Asset] = []
    for asset in assets:
        values = [
            asset.name or "",
            asset.tag or "",
            (asset.asset_type.value if hasattr(asset.asset_type, "value") else str(asset.asset_type)) or "",
        ]
        haystack = " ".join(v.lower() for v in values)
        if needle in haystack:
            filtered.append(asset)

    result: list[TwinState] = []
    for asset in filtered:
        state = await engine.get_state(str(asset.id))
        result.append(state if state else _asset_to_twin(asset))
    return result


@router.post("/", response_model=TwinState)
async def create_twin(
    payload: TwinCreateRequest,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> TwinState:
    """Create/init twin runtime state for an existing asset."""
    asset: Asset | None = None

    if payload.asset_id is not None:
        asset = await session.get(Asset, payload.asset_id)
    elif payload.asset_query and payload.asset_query.strip():
        query = payload.asset_query.strip().lower()
        assets = (await session.execute(select(Asset).where(Asset.is_active.is_(True)))).scalars().all()
        asset = next(
            (
                a
                for a in assets
                if query in (a.name or "").lower()
                or query in (a.tag or "").lower()
                or query in ((a.asset_type.value if hasattr(a.asset_type, "value") else str(a.asset_type)).lower())
            ),
            None,
        )
    else:
        raise HTTPException(status_code=422, detail="Provide asset_id or asset_query")

    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    current = await engine.get_state(str(asset.id))
    if current:
        return current

    initial = await engine.update_state(
        asset_id=str(asset.id),
        datapoints={},
        asset_name=asset.name,
        asset_type=asset.asset_type.value if hasattr(asset.asset_type, "value") else str(asset.asset_type),
    )
    await store.save_state(str(asset.id), initial)
    await store.save_snapshot(str(asset.id), initial)
    return initial


@router.patch("/{asset_id}", response_model=TwinState)
async def update_twin(
    asset_id: uuid.UUID,
    payload: TwinUpdateRequest,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> TwinState:
    """Update twin metadata and/or current values."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    name = payload.asset_name or asset.name
    values = payload.current_values or {}

    state = await engine.update_state(
        asset_id=str(asset.id),
        datapoints=values,
        asset_name=name,
        asset_type=asset.asset_type.value if hasattr(asset.asset_type, "value") else str(asset.asset_type),
    )
    await store.save_state(str(asset.id), state)
    await store.save_snapshot(str(asset.id), state)
    return state


@router.delete("/{asset_id}")
async def delete_twin(
    asset_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> dict[str, str]:
    """Delete/reset runtime twin state for asset."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    await engine.reset_state(str(asset.id))
    return {"detail": "Twin state deleted"}


@router.post("/{asset_id}/activate")
async def activate_twin(
    asset_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> dict[str, str]:
    """Activate asset and ensure twin initialized."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    asset.is_active = True
    asset.status = AssetStatus.ONLINE
    await session.commit()

    existing = await engine.get_state(str(asset.id))
    if existing is None:
        created = await engine.update_state(
            asset_id=str(asset.id),
            datapoints={},
            asset_name=asset.name,
            asset_type=asset.asset_type.value if hasattr(asset.asset_type, "value") else str(asset.asset_type),
        )
        await store.save_state(str(asset.id), created)
        await store.save_snapshot(str(asset.id), created)

    return {"detail": "Twin activated"}


@router.post("/{asset_id}/deactivate")
async def deactivate_twin(
    asset_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> dict[str, str]:
    """Deactivate asset and reset twin runtime state."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    asset.is_active = False
    asset.status = AssetStatus.MAINTENANCE
    await session.commit()

    await engine.reset_state(str(asset.id))
    return {"detail": "Twin deactivated"}


@router.post("/{asset_id}/simulate", response_model=TwinState)
async def simulate_twin(
    asset_id: uuid.UUID,
    n_points: int = Query(default=10, ge=1, le=300),
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> TwinState:
    """Inject simulated datapoints and return latest updated state."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    kind = asset.asset_type.value if hasattr(asset.asset_type, "value") else str(asset.asset_type)
    points = await simulator.simulate_asset(str(asset.id), kind, n_points=n_points)

    latest: TwinState | None = None
    for p in points:
        payload = {k: v for k, v in p.items() if k not in {"asset_id", "timestamp"}}
        latest = await engine.update_state(
            asset_id=str(asset.id),
            datapoints=payload,
            asset_name=asset.name,
            asset_type=kind,
        )
        await store.save_state(str(asset.id), latest)
        await store.save_snapshot(str(asset.id), latest)

    if latest is None:
        raise HTTPException(status_code=500, detail="Simulation produced no datapoints")

    events = await engine.get_recent_events(5)
    for event in events:
        await store.publish_event(event)

    return latest


@router.get("/{asset_id}/history", response_model=list[TwinState])
async def get_twin_history(
    asset_id: uuid.UUID,
    n: int = Query(default=100, ge=1, le=1000),
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> list[TwinState]:
    """Get latest N state snapshots for one twin."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    mem_history = await engine.get_history(str(asset_id), n=n)
    if mem_history:
        return mem_history

    return await store.get_history(str(asset_id), n=n)


@router.get("/{asset_id}/baseline", response_model=list[TwinBaseline])
async def get_or_compute_baseline(
    asset_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> list[TwinBaseline]:
    """Get baseline if exists, otherwise compute from buffered datapoints."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    baseline = await engine.get_baseline(str(asset_id))
    if baseline:
        return baseline

    computed = await engine.compute_baseline(str(asset_id))
    return computed


@router.post("/{asset_id}/reset")
async def reset_twin(
    asset_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _: User = Depends(get_current_user),
) -> dict[str, str]:
    """Reset one in-memory twin state."""
    asset = await session.get(Asset, asset_id)
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")

    await engine.reset_state(str(asset_id))
    return {"detail": "Twin state reset"}


@router.websocket("/ws/live")
async def twins_live_ws(websocket: WebSocket) -> None:
    """Push live twin states every second."""
    await websocket.accept()
    try:
        while True:
            states = await engine.get_all_states()
            payload: list[dict[str, Any]] = [state.model_dump(mode="json") for state in states]
            await websocket.send_json({"type": "live_states", "timestamp": utcnow().isoformat(), "data": payload})
            await asyncio.sleep(1)
    except WebSocketDisconnect:
        return
    except Exception:
        await websocket.close()
