// ControlTwin — twins.js — generated by Blackbox
import apiClient from "../lib/axios";

export async function getAllTwins() {
  const { data } = await apiClient.get("/twins/");
  return data;
}

export async function getTwin(assetId) {
  const { data } = await apiClient.get(`/twins/${assetId}`);
  return data;
}

export async function simulateTwin(assetId, nPoints = 10) {
  const { data } = await apiClient.post(`/twins/${assetId}/simulate`, null, {
    params: { n_points: nPoints },
  });
  return data;
}

export async function getTwinHistory(assetId, n = 100) {
  const { data } = await apiClient.get(`/twins/${assetId}/history`, {
    params: { n },
  });
  return data;
}

export async function getTwinBaseline(assetId) {
  const { data } = await apiClient.get(`/twins/${assetId}/baseline`);
  return data;
}

export async function resetTwin(assetId) {
  const { data } = await apiClient.post(`/twins/${assetId}/reset`);
  return data;
}

export async function searchTwins(query = "") {
  const { data } = await apiClient.get("/twins/search", {
    params: { q: query },
  });
  return data;
}

function isUuid(value) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
    String(value || "").trim()
  );
}

export async function createTwin(assetInput) {
  const raw = String(assetInput || "").trim();
  const payload = isUuid(raw) ? { asset_id: raw } : { asset_query: raw };
  const { data } = await apiClient.post("/twins/", payload);
  return data;
}

export async function updateTwin(assetId, payload) {
  const { data } = await apiClient.patch(`/twins/${assetId}`, payload);
  return data;
}

export async function deleteTwin(assetId) {
  const { data } = await apiClient.delete(`/twins/${assetId}`);
  return data;
}

export async function activateTwin(assetId) {
  const { data } = await apiClient.post(`/twins/${assetId}/activate`);
  return data;
}

export async function deactivateTwin(assetId) {
  const { data } = await apiClient.post(`/twins/${assetId}/deactivate`);
  return data;
}

export function connectTwinWebSocket(onMessage) {
  const ws = new WebSocket("ws://localhost:8000/api/v1/twins/ws/live");
  ws.onmessage = (event) => {
    try {
      const parsed = JSON.parse(event.data);
      if (onMessage) onMessage(parsed);
    } catch (_err) {
      // no-op
    }
  };
  return ws;
}
